import { createActionConst } from '../../../utils/action.utils';

const PUBLICATION_ACTIVITIES_NAMESPACE = 'PUBLICATION_ACTIVITIES_NAMESPACE';

export const STORE_PUBLICATION_ACTIVITIES = createActionConst(
  PUBLICATION_ACTIVITIES_NAMESPACE,
  'STORE_PUBLICATION_ACTIVITIES',
);
export const CLEAR_PUBLICATION_ACTIVITIES = createActionConst(
  PUBLICATION_ACTIVITIES_NAMESPACE,
  'CLEAR_PUBLICATION_ACTIVITIES',
);
