import { createActionConst } from '../../../utils/action.utils';

const PROFILE_NAMESPACE = 'PROFILE';

export const SETUP_PROFILE_PAGE = createActionConst(PROFILE_NAMESPACE, 'SEARCH_USER');

export const UPDATE_USER = createActionConst(PROFILE_NAMESPACE, 'UPDATE_USER');
export const DELETE_USER = createActionConst(PROFILE_NAMESPACE, 'DELETE_USER');

export const CREATE_PUBLICATION = createActionConst(PROFILE_NAMESPACE, 'CREATE_PUBLICATION');
export const UPDATE_PUBLICATION = createActionConst(PROFILE_NAMESPACE, 'UPDATE_PUBLICATION');
export const DELETE_PUBLICATION = createActionConst(PROFILE_NAMESPACE, 'DELETE_PUBLICATION');

export const STORE_SEARCHED_USER = createActionConst(PROFILE_NAMESPACE, 'STORE_SEARCHED_USER');
export const CLEAR_SEARCHED_USER = createActionConst(PROFILE_NAMESPACE, 'CLEAR_SEARCHED_USER');

export const STORE_SEARCHED_PUBLICATIONS = createActionConst(PROFILE_NAMESPACE, 'STORE_SEARCHED_PUBLICATIONS');
export const CLEAR_SEARCHED_PUBLICATIONS = createActionConst(PROFILE_NAMESPACE, 'CLEAR_SEARCHED_PUBLICATIONS');

export const STORE_SEARCHED_ACTIVITIES = createActionConst(PROFILE_NAMESPACE, 'STORE_SEARCHED_ACTIVITIES');
export const CLEAR_SEARCHED_ACTIVITIES = createActionConst(PROFILE_NAMESPACE, 'CLEAR_SEARCHED_ACTIVITIES');

export const GET_USERS = createActionConst(PROFILE_NAMESPACE, 'GET_USERS');
export const STORE_USERS = createActionConst(PROFILE_NAMESPACE, 'STORE_USERS');
export const CLEAR_USERS = createActionConst(PROFILE_NAMESPACE, 'CLEAR_USERS');
